create extension if not exists pg_cron with schema pg_catalog;
create extension if not exists pg_net with schema extensions;
create extension if not exists supabase_vault with schema vault;

alter table public.profiles
  add column daily_prompts_enabled boolean not null default false,
  add column weekly_review_enabled boolean not null default false,
  add column weekly_review_day smallint not null default 7,
  add column weekly_review_time time(0) without time zone not null default '19:00:00',
  add column habit_onboarding_completed boolean not null default false,
  add column last_welcome_back_date date;

alter table public.profiles
  add constraint profiles_weekly_review_day_valid
  check (weekly_review_day between 1 and 7);

create table public.prompts (
  id bigint generated by default as identity primary key,
  body text not null unique check (char_length(body) between 12 and 240),
  category text not null check (category in (
    'ordinary-moments',
    'people',
    'places',
    'work-and-learning',
    'growth',
    'challenges',
    'joy',
    'senses-and-seasons',
    'memories-and-traditions',
    'hopes-and-future'
  )),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.daily_prompt_assignments (
  user_id uuid not null references auth.users (id) on delete cascade,
  entry_date date not null,
  prompt_id bigint not null references public.prompts (id),
  created_at timestamptz not null default now(),
  refreshed_at timestamptz,
  primary key (user_id, entry_date)
);

create index daily_prompt_assignments_recent_idx
  on public.daily_prompt_assignments (user_id, entry_date desc);

create table public.email_deliveries (
  id uuid primary key default extensions.gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  kind text not null default 'weekly-review' check (kind = 'weekly-review'),
  review_date date not null,
  period_start date not null,
  period_end date not null,
  status text not null default 'pending' check (status in ('pending', 'sent', 'failed')),
  attempts smallint not null default 1 check (attempts between 1 and 5),
  next_attempt_at timestamptz,
  provider_id text,
  last_error_code text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, kind, review_date),
  check (period_end >= period_start)
);

create index email_deliveries_retry_idx
  on public.email_deliveries (status, next_attempt_at)
  where status <> 'sent';

create table public.product_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete cascade,
  session_id uuid,
  event_name text not null check (event_name in (
    'editor_started',
    'twenty_five_words_reached',
    'hundred_words_reached',
    'signup_started',
    'signup_completed',
    'returned_next_day',
    'seven_days_completed'
  )),
  entry_date date,
  dedupe_key text not null unique,
  occurred_at timestamptz not null default now(),
  check (user_id is not null or session_id is not null)
);

create index product_events_name_time_idx
  on public.product_events (event_name, occurred_at desc);

alter table public.prompts enable row level security;
alter table public.daily_prompt_assignments enable row level security;
alter table public.email_deliveries enable row level security;
alter table public.product_events enable row level security;

revoke all on table public.prompts from anon, authenticated;
revoke all on table public.daily_prompt_assignments from anon, authenticated;
revoke all on table public.email_deliveries from anon, authenticated;
revoke all on table public.product_events from anon, authenticated;

grant select on table public.prompts to authenticated;
grant select on table public.daily_prompt_assignments to authenticated;
grant all on table public.prompts to service_role;
grant all on table public.daily_prompt_assignments to service_role;
grant all on table public.email_deliveries to service_role;
grant all on table public.product_events to service_role;

create policy "Authenticated users can read active prompts"
  on public.prompts
  for select
  to authenticated
  using (active);

create policy "Users can read their own prompt assignments"
  on public.daily_prompt_assignments
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create or replace function public.habit_streaks(
  p_user_id uuid,
  p_today date
)
returns table (current_streak integer, longest_streak integer)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_cursor date;
  v_date date;
  v_previous date;
  v_run integer := 0;
begin
  if p_user_id is null or p_today is null then
    return query select 0, 0;
    return;
  end if;

  if exists (
    select 1 from public.entries
    where user_id = p_user_id and entry_date = p_today and word_count >= 100
  ) then
    v_cursor := p_today;
  else
    v_cursor := p_today - 1;
  end if;

  current_streak := 0;
  while exists (
    select 1 from public.entries
    where user_id = p_user_id and entry_date = v_cursor and word_count >= 100
  ) loop
    current_streak := current_streak + 1;
    v_cursor := v_cursor - 1;
  end loop;

  longest_streak := 0;
  for v_date in
    select entry_date
    from public.entries
    where user_id = p_user_id and word_count >= 100
    order by entry_date
  loop
    if v_previous is not null and v_date = v_previous + 1 then
      v_run := v_run + 1;
    else
      v_run := 1;
    end if;
    longest_streak := greatest(longest_streak, v_run);
    v_previous := v_date;
  end loop;

  return next;
end;
$$;

create or replace function public.set_habit_preferences(
  p_daily_prompts_enabled boolean,
  p_weekly_review_enabled boolean,
  p_weekly_review_day smallint,
  p_weekly_review_time time without time zone,
  p_habit_onboarding_completed boolean
)
returns public.profiles
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_profile public.profiles;
begin
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;

  if p_daily_prompts_enabled is null
    or p_weekly_review_enabled is null
    or p_habit_onboarding_completed is null
    or p_weekly_review_day not between 1 and 7
    or p_weekly_review_time is null then
    raise exception 'Valid habit preferences are required' using errcode = '22023';
  end if;

  update public.profiles
  set daily_prompts_enabled = p_daily_prompts_enabled,
      weekly_review_enabled = p_weekly_review_enabled,
      weekly_review_day = p_weekly_review_day,
      weekly_review_time = p_weekly_review_time,
      habit_onboarding_completed = p_habit_onboarding_completed,
      updated_at = now()
  where user_id = v_user_id
  returning * into v_profile;

  if not found then
    raise exception 'Profile required' using errcode = 'P0002';
  end if;

  return v_profile;
end;
$$;

create or replace function public.mark_welcome_back(p_entry_date date)
returns date
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_today date;
begin
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;

  select (now() at time zone timezone)::date
  into v_today
  from public.profiles
  where user_id = v_user_id;

  if v_today is null or p_entry_date is distinct from v_today then
    raise exception 'Welcome-back date must be today' using errcode = '22023';
  end if;

  update public.profiles
  set last_welcome_back_date = p_entry_date,
      updated_at = now()
  where user_id = v_user_id;

  return p_entry_date;
end;
$$;

create or replace function public.get_daily_prompt(
  p_entry_date date,
  p_refresh boolean default false
)
returns public.prompts
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_profile public.profiles;
  v_existing bigint;
  v_prompt public.prompts;
begin
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;

  select * into v_profile
  from public.profiles
  where user_id = v_user_id;

  if not found then
    raise exception 'Profile required' using errcode = 'P0002';
  end if;

  select prompt_id into v_existing
  from public.daily_prompt_assignments
  where user_id = v_user_id and entry_date = p_entry_date;

  if v_existing is not null and not coalesce(p_refresh, false) then
    select * into v_prompt from public.prompts where id = v_existing;
    return v_prompt;
  end if;

  if p_entry_date <> (now() at time zone v_profile.timezone)::date then
    if coalesce(p_refresh, false) then
      raise exception 'Past prompts cannot be refreshed' using errcode = '22023';
    end if;
    return null;
  end if;

  if not v_profile.daily_prompts_enabled then
    return null;
  end if;

  select p.* into v_prompt
  from public.prompts p
  where p.active
    and p.id is distinct from v_existing
    and not exists (
      select 1
      from public.daily_prompt_assignments a
      where a.user_id = v_user_id
        and a.entry_date between p_entry_date - 30 and p_entry_date - 1
        and a.prompt_id = p.id
    )
  order by random()
  limit 1;

  if v_prompt.id is null then
    select p.* into v_prompt
    from public.prompts p
    where p.active and p.id is distinct from v_existing
    order by random()
    limit 1;
  end if;

  if v_prompt.id is null then
    return null;
  end if;

  insert into public.daily_prompt_assignments (
    user_id, entry_date, prompt_id, refreshed_at
  ) values (
    v_user_id,
    p_entry_date,
    v_prompt.id,
    case when v_existing is null then null else now() end
  )
  on conflict (user_id, entry_date) do update
  set prompt_id = excluded.prompt_id,
      refreshed_at = now();

  return v_prompt;
end;
$$;

create or replace function public.get_habit_dashboard(p_month date default null)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_profile public.profiles;
  v_today date;
  v_month_start date;
  v_month_end date;
  v_year_start date;
  v_current_streak integer := 0;
  v_longest_streak integer := 0;
  v_first_entry date;
  v_last_completed date;
  v_total_words bigint := 0;
  v_total_completed integer := 0;
  v_month_words bigint := 0;
  v_month_completed integer := 0;
  v_year_words bigint := 0;
  v_year_completed integer := 0;
  v_calendar jsonb := '[]'::jsonb;
begin
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;

  select * into v_profile
  from public.profiles
  where user_id = v_user_id;

  if not found then
    raise exception 'Profile required' using errcode = 'P0002';
  end if;

  v_today := (now() at time zone v_profile.timezone)::date;
  v_month_start := date_trunc('month', coalesce(p_month, v_today))::date;
  v_month_end := (v_month_start + interval '1 month - 1 day')::date;
  v_year_start := date_trunc('year', v_today)::date;

  select current_streak, longest_streak
  into v_current_streak, v_longest_streak
  from public.habit_streaks(v_user_id, v_today);

  select min(entry_date), max(entry_date) filter (where word_count >= 100),
         coalesce(sum(word_count), 0), count(*) filter (where word_count >= 100)
  into v_first_entry, v_last_completed, v_total_words, v_total_completed
  from public.entries
  where user_id = v_user_id;

  select coalesce(sum(word_count), 0), count(*) filter (where word_count >= 100)
  into v_month_words, v_month_completed
  from public.entries
  where user_id = v_user_id
    and entry_date between date_trunc('month', v_today)::date and v_today;

  select coalesce(sum(word_count), 0), count(*) filter (where word_count >= 100)
  into v_year_words, v_year_completed
  from public.entries
  where user_id = v_user_id
    and entry_date between v_year_start and v_today;

  select coalesce(jsonb_agg(jsonb_build_object(
    'entryDate', entry_date,
    'wordCount', word_count,
    'completed', word_count >= 100
  ) order by entry_date), '[]'::jsonb)
  into v_calendar
  from public.entries
  where user_id = v_user_id
    and entry_date between v_month_start and v_month_end;

  return jsonb_build_object(
    'today', v_today,
    'visibleMonth', v_month_start,
    'currentStreak', v_current_streak,
    'longestStreak', v_longest_streak,
    'firstEntryDate', v_first_entry,
    'lastCompletedDate', v_last_completed,
    'missedDays', case
      when v_last_completed is null then 0
      else greatest(v_today - v_last_completed - 1, 0)
    end,
    'lastWelcomeBackDate', v_profile.last_welcome_back_date,
    'totalWords', v_total_words,
    'totalCompletedDays', v_total_completed,
    'monthWords', v_month_words,
    'monthCompletedDays', v_month_completed,
    'monthElapsedDays', extract(day from v_today)::integer,
    'yearWords', v_year_words,
    'yearCompletedDays', v_year_completed,
    'yearElapsedDays', extract(doy from v_today)::integer,
    'calendar', v_calendar
  );
end;
$$;

create or replace function public.record_product_event(
  p_event_name text,
  p_session_id uuid default null,
  p_entry_date date default null
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_actor text;
  v_key text;
  v_inserted bigint;
begin
  if p_event_name not in (
    'editor_started',
    'twenty_five_words_reached',
    'hundred_words_reached',
    'signup_started',
    'signup_completed',
    'returned_next_day',
    'seven_days_completed'
  ) then
    raise exception 'Unknown product event' using errcode = '22023';
  end if;

  if v_user_id is null and p_session_id is null then
    raise exception 'A session identifier is required' using errcode = '22023';
  end if;

  if p_entry_date is not null
    and (p_entry_date < current_date - 730 or p_entry_date > current_date + 1) then
    raise exception 'Event date is outside the accepted range' using errcode = '22023';
  end if;

  v_actor := coalesce(v_user_id::text, p_session_id::text);
  v_key := p_event_name || ':' || v_actor || ':' || coalesce(p_entry_date::text, 'session');

  insert into public.product_events (
    user_id, session_id, event_name, entry_date, dedupe_key
  ) values (
    v_user_id, p_session_id, p_event_name, p_entry_date, v_key
  )
  on conflict (dedupe_key) do nothing
  returning id into v_inserted;

  return v_inserted is not null;
end;
$$;

create or replace function public.claim_due_weekly_reviews(
  p_now timestamptz default now(),
  p_limit integer default 50
)
returns table (
  delivery_id uuid,
  user_id uuid,
  email text,
  review_date date,
  period_start date,
  period_end date,
  timezone text,
  current_streak integer,
  week_completed integer,
  week_words bigint,
  month_completed integer,
  month_words bigint,
  year_completed integer,
  year_words bigint
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_candidate record;
  v_delivery public.email_deliveries;
  v_streak integer;
begin
  delete from public.product_events where occurred_at < p_now - interval '18 months';
  delete from public.email_deliveries where created_at < p_now - interval '90 days';

  for v_candidate in
    select p.*, u.email,
           p_now at time zone p.timezone as local_now
    from public.profiles p
    join auth.users u on u.id = p.user_id
    where p.weekly_review_enabled
      and u.email is not null
      and extract(isodow from (p_now at time zone p.timezone))::integer = p.weekly_review_day
      and (p_now at time zone p.timezone)::time >= p.weekly_review_time
      and (p_now at time zone p.timezone) <
        date_trunc('day', p_now at time zone p.timezone)
        + p.weekly_review_time + interval '24 hours'
    order by p.user_id
    limit greatest(1, least(coalesce(p_limit, 50), 100))
  loop
    insert into public.email_deliveries (
      user_id, review_date, period_start, period_end
    ) values (
      v_candidate.user_id,
      v_candidate.local_now::date,
      v_candidate.local_now::date - 6,
      v_candidate.local_now::date
    )
    on conflict on constraint email_deliveries_user_id_kind_review_date_key do update
    set status = 'pending',
        attempts = public.email_deliveries.attempts + 1,
        next_attempt_at = null,
        updated_at = p_now
    where (
        public.email_deliveries.status = 'failed'
        and public.email_deliveries.attempts < 5
        and public.email_deliveries.next_attempt_at <= p_now
      ) or (
        public.email_deliveries.status = 'pending'
        and public.email_deliveries.attempts < 5
        and public.email_deliveries.updated_at < p_now - interval '10 minutes'
      )
    returning * into v_delivery;

    if v_delivery.id is null then
      continue;
    end if;

    select s.current_streak into v_streak
    from public.habit_streaks(v_candidate.user_id, v_candidate.local_now::date) s;

    delivery_id := v_delivery.id;
    user_id := v_candidate.user_id;
    email := v_candidate.email;
    review_date := v_delivery.review_date;
    period_start := v_delivery.period_start;
    period_end := v_delivery.period_end;
    timezone := v_candidate.timezone;
    current_streak := coalesce(v_streak, 0);

    select count(*) filter (where word_count >= 100), coalesce(sum(word_count), 0)
    into week_completed, week_words
    from public.entries
    where entries.user_id = v_candidate.user_id
      and entry_date between v_delivery.period_start and v_delivery.period_end;

    select count(*) filter (where word_count >= 100), coalesce(sum(word_count), 0)
    into month_completed, month_words
    from public.entries
    where entries.user_id = v_candidate.user_id
      and entry_date between date_trunc('month', v_delivery.review_date)::date and v_delivery.review_date;

    select count(*) filter (where word_count >= 100), coalesce(sum(word_count), 0)
    into year_completed, year_words
    from public.entries
    where entries.user_id = v_candidate.user_id
      and entry_date between date_trunc('year', v_delivery.review_date)::date and v_delivery.review_date;

    return next;
  end loop;
end;
$$;

create or replace function public.finish_weekly_review(
  p_delivery_id uuid,
  p_provider_id text default null,
  p_error_code text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_delivery_id is null then
    raise exception 'Delivery identifier required' using errcode = '22023';
  end if;

  if p_error_code is null then
    update public.email_deliveries
    set status = 'sent',
        provider_id = left(p_provider_id, 160),
        last_error_code = null,
        next_attempt_at = null,
        sent_at = now(),
        updated_at = now()
    where id = p_delivery_id;
  else
    update public.email_deliveries
    set status = 'failed',
        last_error_code = left(p_error_code, 80),
        next_attempt_at = case
          when attempts >= 5 then null
          else now() + make_interval(mins => least(30, power(2, attempts)::integer))
        end,
        updated_at = now()
    where id = p_delivery_id;
  end if;
end;
$$;

create or replace function public.save_entry(
  p_entry_date date,
  p_content text,
  p_word_count integer,
  p_expected_version bigint
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_existing public.entries;
  v_saved public.entries;
begin
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;

  if p_entry_date is null or p_content is null or p_word_count is null then
    raise exception 'Entry date, content, and word count are required' using errcode = '22004';
  end if;

  if p_word_count < 0 then
    raise exception 'Word count cannot be negative' using errcode = '22023';
  end if;

  select * into v_existing
  from public.entries
  where user_id = v_user_id and entry_date = p_entry_date
  for update;

  if not found then
    if coalesce(p_expected_version, 0) <> 0 then
      return jsonb_build_object('status', 'conflict', 'remote', null);
    end if;

    begin
      insert into public.entries (
        user_id, entry_date, content, word_count, completed_at
      ) values (
        v_user_id,
        p_entry_date,
        p_content,
        p_word_count,
        case when p_word_count >= 100 then now() else null end
      )
      returning * into v_saved;
      return jsonb_build_object('status', 'saved', 'entry', to_jsonb(v_saved));
    exception when unique_violation then
      select * into v_existing
      from public.entries
      where user_id = v_user_id and entry_date = p_entry_date;
      return jsonb_build_object('status', 'conflict', 'remote', to_jsonb(v_existing));
    end;
  end if;

  if v_existing.version <> coalesce(p_expected_version, 0) then
    return jsonb_build_object('status', 'conflict', 'remote', to_jsonb(v_existing));
  end if;

  update public.entries
  set content = p_content,
      word_count = p_word_count,
      completed_at = case
        when p_word_count >= 100 then coalesce(completed_at, now())
        else null
      end,
      version = version + 1,
      updated_at = now()
  where id = v_existing.id
  returning * into v_saved;

  return jsonb_build_object('status', 'saved', 'entry', to_jsonb(v_saved));
end;
$$;

create or replace view public.product_metrics_daily
with (security_invoker = true)
as
select occurred_at::date as event_date,
       event_name,
       count(*)::bigint as event_count,
       count(distinct coalesce(user_id::text, session_id::text))::bigint as actor_count
from public.product_events
group by occurred_at::date, event_name;

revoke all on table public.product_metrics_daily from anon, authenticated;
grant select on table public.product_metrics_daily to service_role;

revoke all on function public.habit_streaks(uuid, date) from public;
revoke all on function public.set_habit_preferences(boolean, boolean, smallint, time without time zone, boolean) from public;
revoke all on function public.mark_welcome_back(date) from public;
revoke all on function public.get_daily_prompt(date, boolean) from public;
revoke all on function public.get_habit_dashboard(date) from public;
revoke all on function public.record_product_event(text, uuid, date) from public;
revoke all on function public.claim_due_weekly_reviews(timestamptz, integer) from public;
revoke all on function public.finish_weekly_review(uuid, text, text) from public;

grant execute on function public.set_habit_preferences(boolean, boolean, smallint, time without time zone, boolean) to authenticated;
grant execute on function public.mark_welcome_back(date) to authenticated;
grant execute on function public.get_daily_prompt(date, boolean) to authenticated;
grant execute on function public.get_habit_dashboard(date) to authenticated;
grant execute on function public.record_product_event(text, uuid, date) to anon, authenticated;
grant execute on function public.habit_streaks(uuid, date) to service_role;
grant execute on function public.claim_due_weekly_reviews(timestamptz, integer) to service_role;
grant execute on function public.finish_weekly_review(uuid, text, text) to service_role;
