insert into public.prompts (category, body) values
  ('ordinary-moments', 'Describe one ordinary moment from today that you would like to remember.'),
  ('ordinary-moments', 'What small task shaped the rhythm of your day?'),
  ('ordinary-moments', 'Write about something you noticed while moving from one place to another.'),
  ('ordinary-moments', 'Which part of your routine felt especially comforting today?'),
  ('ordinary-moments', 'Describe the first ten minutes after you woke up.'),
  ('ordinary-moments', 'What was on the table, desk, or counter nearest you today?'),
  ('ordinary-moments', 'Capture a brief conversation that might otherwise be forgotten.'),
  ('ordinary-moments', 'What did you wait for today, and what happened while you waited?'),
  ('ordinary-moments', 'Describe a choice you made without giving it much thought.'),
  ('ordinary-moments', 'What familiar object did you use today, and what history does it carry?'),
  ('ordinary-moments', 'Write about the quietest part of your day.'),
  ('ordinary-moments', 'What did you eat or drink, and where were you?'),
  ('ordinary-moments', 'Describe a moment when your plans changed slightly.'),
  ('ordinary-moments', 'What tiny detail made today different from yesterday?'),
  ('ordinary-moments', 'If today were represented by one scene, what would be in it?'),
  ('people', 'Who made your day easier, even in a small way?'),
  ('people', 'Write about someone whose expression or tone stayed with you today.'),
  ('people', 'What did you learn about another person recently?'),
  ('people', 'Describe a kindness you gave, received, or witnessed.'),
  ('people', 'Who would understand the story of your day best, and why?'),
  ('people', 'Write about a person you thought of today but did not contact.'),
  ('people', 'What recent conversation deserves a place in your year?'),
  ('people', 'Describe a shared joke, silence, or routine with someone close to you.'),
  ('people', 'Who challenged your thinking today?'),
  ('people', 'What quality did you appreciate in someone today?'),
  ('people', 'Write about a person who helped shape one of your habits.'),
  ('people', 'What would you like to thank someone for right now?'),
  ('people', 'Describe how a relationship has changed in a small but meaningful way.'),
  ('people', 'Who did you miss today, and what brought them to mind?'),
  ('people', 'What is one story about someone you never want to forget?'),
  ('places', 'Describe the place where you spent most of today.'),
  ('places', 'What corner of your home feels most like yours?'),
  ('places', 'Write about a route you know well and what you notice along it.'),
  ('places', 'Which place made you feel calm today?'),
  ('places', 'Describe a room through its light, sounds, and objects.'),
  ('places', 'What place from your past did today remind you of?'),
  ('places', 'Write about somewhere nearby that you would like to explore.'),
  ('places', 'How has a familiar place changed since you first knew it?'),
  ('places', 'Describe the view from a window you looked through today.'),
  ('places', 'What makes a place feel welcoming to you?'),
  ('places', 'Write about the most crowded or most empty place you saw today.'),
  ('places', 'Which place holds an important family or personal story?'),
  ('places', 'Describe a threshold you crossed today: a door, station, gate, or boundary.'),
  ('places', 'If you could preserve one place exactly as it is now, which would it be?'),
  ('places', 'What location best matches the mood of your day?'),
  ('work-and-learning', 'What problem did you make progress on today?'),
  ('work-and-learning', 'Describe something you understand better now than you did this morning.'),
  ('work-and-learning', 'What part of your work or study required the most attention?'),
  ('work-and-learning', 'Write about a useful mistake you made recently.'),
  ('work-and-learning', 'Who taught you something today, directly or indirectly?'),
  ('work-and-learning', 'What skill are you slowly becoming more confident in?'),
  ('work-and-learning', 'Describe a decision you made with incomplete information.'),
  ('work-and-learning', 'What question kept returning to you today?'),
  ('work-and-learning', 'Write about one task you finished and how completion felt.'),
  ('work-and-learning', 'What did you postpone, and what made it difficult to begin?'),
  ('work-and-learning', 'Describe an idea worth revisiting later.'),
  ('work-and-learning', 'What advice would have helped you at the start of today?'),
  ('work-and-learning', 'Write about a moment when collaboration changed the outcome.'),
  ('work-and-learning', 'What are you practicing that no one else can easily see?'),
  ('work-and-learning', 'Which part of today made you feel capable?'),
  ('growth', 'What are you handling differently than you would have a year ago?'),
  ('growth', 'Describe a boundary that has become clearer to you.'),
  ('growth', 'What recent choice reflects the person you are becoming?'),
  ('growth', 'Write about something you are learning to accept.'),
  ('growth', 'What habit is quietly improving your days?'),
  ('growth', 'Describe a moment when you changed your mind.'),
  ('growth', 'What feels easier now because you kept practicing?'),
  ('growth', 'Write about a fear that has become more manageable.'),
  ('growth', 'What do you want to make more room for in your life?'),
  ('growth', 'Describe one way you showed patience with yourself today.'),
  ('growth', 'What expectation are you ready to reconsider?'),
  ('growth', 'Write about a recent moment of quiet courage.'),
  ('growth', 'What have you outgrown without fully noticing?'),
  ('growth', 'Describe a lesson you hope to carry into next month.'),
  ('growth', 'What would your past self be glad to know about today?'),
  ('challenges', 'What was the hardest part of today, stated simply and honestly?'),
  ('challenges', 'Describe how you responded when something did not go as planned.'),
  ('challenges', 'What is taking more energy than usual right now?'),
  ('challenges', 'Write about a problem that still feels unfinished.'),
  ('challenges', 'What helped you continue when your motivation was low?'),
  ('challenges', 'Describe a moment when you needed to pause.'),
  ('challenges', 'What can you control about a difficult situation, and what can you release?'),
  ('challenges', 'Write about something you did even though it felt uncomfortable.'),
  ('challenges', 'What support would make tomorrow feel more manageable?'),
  ('challenges', 'Describe a setback without turning it into a judgment about yourself.'),
  ('challenges', 'What did today ask you to be patient with?'),
  ('challenges', 'Write about a difficult choice and the values behind it.'),
  ('challenges', 'What uncertainty are you carrying at the moment?'),
  ('challenges', 'Describe one practical next step for something that feels complicated.'),
  ('challenges', 'What did you learn from a moment of frustration today?'),
  ('joy', 'What made you smile before you had time to think about it?'),
  ('joy', 'Describe a small pleasure you would happily repeat tomorrow.'),
  ('joy', 'What felt unexpectedly generous or abundant today?'),
  ('joy', 'Write about a sound, taste, sight, or texture you enjoyed.'),
  ('joy', 'Which moment today felt most alive?'),
  ('joy', 'What are you looking forward to right now?'),
  ('joy', 'Describe something simple that made you feel fortunate.'),
  ('joy', 'What recent memory still makes you laugh?'),
  ('joy', 'Write about an activity that helps you lose track of time.'),
  ('joy', 'Who or what brought warmth into your day?'),
  ('joy', 'Describe a moment that felt lighter than expected.'),
  ('joy', 'What beauty did you notice in an ordinary setting?'),
  ('joy', 'Write about something you are proud to have completed.'),
  ('joy', 'What would make today worth revisiting years from now?'),
  ('joy', 'Describe the best part of your day without minimizing it.'),
  ('senses-and-seasons', 'What did the air feel like when you first stepped outside?'),
  ('senses-and-seasons', 'Describe today using three colors and explain your choices.'),
  ('senses-and-seasons', 'What sound defined a particular moment today?'),
  ('senses-and-seasons', 'Write about the weather and how it changed your plans or mood.'),
  ('senses-and-seasons', 'What scent brought back a memory today?'),
  ('senses-and-seasons', 'Describe the light at the beginning or end of your day.'),
  ('senses-and-seasons', 'What seasonal change have you noticed recently?'),
  ('senses-and-seasons', 'Write about a texture your hands remember from today.'),
  ('senses-and-seasons', 'What was the loudest moment of your day?'),
  ('senses-and-seasons', 'Describe a meal through color, smell, and sound.'),
  ('senses-and-seasons', 'What detail in nature caught your attention?'),
  ('senses-and-seasons', 'Write about the temperature of a room and how it felt to be there.'),
  ('senses-and-seasons', 'How did your surroundings change between morning and evening?'),
  ('senses-and-seasons', 'Describe one moment today as if it were a photograph.'),
  ('senses-and-seasons', 'What sensory detail would bring today back most clearly?'),
  ('memories-and-traditions', 'What family or personal tradition has changed over time?'),
  ('memories-and-traditions', 'Describe a childhood routine you can still remember clearly.'),
  ('memories-and-traditions', 'What object connects you to an earlier chapter of your life?'),
  ('memories-and-traditions', 'Write about a celebration that felt especially meaningful.'),
  ('memories-and-traditions', 'What phrase or saying from someone you know has stayed with you?'),
  ('memories-and-traditions', 'Describe a meal that carries a strong memory.'),
  ('memories-and-traditions', 'What did your home feel like during a particular season growing up?'),
  ('memories-and-traditions', 'Write about a first experience you still remember.'),
  ('memories-and-traditions', 'Which old photograph would you like to know more about?'),
  ('memories-and-traditions', 'Describe a tradition you would like to continue or begin.'),
  ('memories-and-traditions', 'What song belongs to a specific period of your life?'),
  ('memories-and-traditions', 'Write about a journey whose details remain vivid.'),
  ('memories-and-traditions', 'What everyday item reminds you of someone important?'),
  ('memories-and-traditions', 'Describe a place that no longer exists as you remember it.'),
  ('memories-and-traditions', 'What story from your life do you want future you to remember accurately?'),
  ('hopes-and-future', 'What would make tomorrow feel meaningful rather than merely busy?'),
  ('hopes-and-future', 'Describe something you hope will be different by this time next year.'),
  ('hopes-and-future', 'What are you building slowly, one day at a time?'),
  ('hopes-and-future', 'Write about a possibility you want to take seriously.'),
  ('hopes-and-future', 'What promise would you like to make to your future self?'),
  ('hopes-and-future', 'Describe a place you hope to see and why it matters to you.'),
  ('hopes-and-future', 'What relationship would you like to nurture more intentionally?'),
  ('hopes-and-future', 'Write about a skill or subject you hope to learn.'),
  ('hopes-and-future', 'What would a calmer version of next week look like?'),
  ('hopes-and-future', 'Describe one change that could make your daily life kinder.'),
  ('hopes-and-future', 'What do you hope people remember about this season of your life?'),
  ('hopes-and-future', 'Write about a goal and the feeling you hope it creates.'),
  ('hopes-and-future', 'What are you willing to begin before you feel completely ready?'),
  ('hopes-and-future', 'Describe a future ordinary day you would be happy to live.'),
  ('hopes-and-future', 'What do you want the final page of this year to say?')
on conflict (body) do update
set category = excluded.category,
    active = true;
