alter table public.legal_document_versions
  add column if not exists account_gate_from timestamptz;

update public.legal_document_versions
set is_current = false
where document_type = 'privacy'
  and is_current;

insert into public.legal_document_versions (
  document_type, version, effective_date, is_current, account_gate_from
) values (
  'privacy', '2026-08-18', '2026-08-18', true, '2026-08-18 19:00:00+00'
)
on conflict (document_type, version) do update
set effective_date = excluded.effective_date,
    is_current = excluded.is_current,
    account_gate_from = excluded.account_gate_from;

create table public.media_entitlements (
  user_id uuid primary key references auth.users (id) on delete cascade,
  tier text not null default 'premium' check (tier = 'premium'),
  expires_at timestamptz,
  granted_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.entry_media (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  entry_id uuid not null unique references public.entries (id) on delete cascade,
  storage_path text not null unique,
  mime_type text not null default 'image/webp' check (mime_type = 'image/webp'),
  byte_size integer not null check (byte_size between 1 and 1000000),
  width integer not null check (width between 1 and 2500),
  height integer not null check (height between 1 and 2500),
  version bigint not null default 1 check (version > 0),
  operation_id uuid not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (storage_path = user_id::text || '/' || entry_id::text || '/' || id::text || '.webp')
);

create index entry_media_user_idx on public.entry_media (user_id, created_at desc);

create table public.media_cleanup_queue (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete set null,
  storage_path text not null unique,
  reason text not null check (reason in ('abandoned', 'removed', 'replaced', 'entry-deleted', 'account-deleted')),
  attempts integer not null default 0 check (attempts >= 0),
  next_attempt_at timestamptz not null default now(),
  last_error_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index media_cleanup_due_idx
  on public.media_cleanup_queue (next_attempt_at, attempts);

create table public.media_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  entry_date date,
  event_name text not null check (event_name in (
    'photo_selected',
    'photo_processing_completed',
    'photo_processing_failed',
    'photo_upload_completed',
    'photo_upload_failed',
    'photo_replaced',
    'photo_removed',
    'free_photo_limit_reached'
  )),
  operation_id uuid not null,
  size_bucket text check (size_bucket is null or size_bucket in ('under-250kb', '250-500kb', '500kb-1mb')),
  duration_bucket text check (duration_bucket is null or duration_bucket in ('under-1s', '1-3s', '3-5s', 'over-5s')),
  failure_category text check (failure_category is null or failure_category in (
    'decode', 'format', 'network', 'oversize', 'processing', 'quota', 'server', 'unauthorized'
  )),
  entitlement text not null check (entitlement in ('free', 'premium')),
  dedupe_key text not null unique,
  occurred_at timestamptz not null default now()
);

create index media_events_time_idx on public.media_events (occurred_at desc, event_name);
create index media_events_user_idx on public.media_events (user_id, occurred_at desc);

alter table public.media_entitlements enable row level security;
alter table public.entry_media enable row level security;
alter table public.media_cleanup_queue enable row level security;
alter table public.media_events enable row level security;

revoke all on table public.media_entitlements from anon, authenticated;
revoke all on table public.entry_media from anon, authenticated;
revoke all on table public.media_cleanup_queue from anon, authenticated;
revoke all on table public.media_events from anon, authenticated;

grant select on table public.entry_media to authenticated;
grant all on table public.media_entitlements to service_role;
grant all on table public.entry_media to service_role;
grant all on table public.media_cleanup_queue to service_role;
grant all on table public.media_events to service_role;

create policy "Users can read their own entry media"
on public.entry_media for select to authenticated
using ((select auth.uid()) = user_id);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('journal-media', 'journal-media', false, 1000000, array['image/webp'])
on conflict (id) do update
set public = false,
    file_size_limit = 1000000,
    allowed_mime_types = array['image/webp'];

create or replace function public.owns_journal_media_object(p_name text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.entry_media m
    where m.user_id = auth.uid()
      and m.storage_path = p_name
  );
$$;

create policy "Users can read attached journal media"
on storage.objects for select to authenticated
using (
  bucket_id = 'journal-media'
  and public.owns_journal_media_object(name)
);

create or replace function public.current_media_tier(p_user_id uuid)
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select case when exists (
    select 1
    from public.media_entitlements e
    where e.user_id = p_user_id
      and e.tier = 'premium'
      and (e.expires_at is null or e.expires_at > now())
  ) then 'premium' else 'free' end;
$$;

create or replace function public.get_media_account_status()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_tier text;
  v_count integer;
  v_privacy_version text;
  v_accepted boolean;
begin
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;

  v_tier := public.current_media_tier(v_user_id);
  select count(*) into v_count from public.entry_media where user_id = v_user_id;
  select version into v_privacy_version
  from public.legal_document_versions
  where document_type = 'privacy' and is_current;
  select exists (
    select 1 from public.legal_acceptances
    where user_id = v_user_id
      and document_type = 'privacy'
      and version = v_privacy_version
  ) into v_accepted;

  return jsonb_build_object(
    'tier', v_tier,
    'storedCount', v_count,
    'limit', case when v_tier = 'free' then 10 else null end,
    'canAdd', v_tier = 'premium' or v_count < 10,
    'privacyAccepted', v_accepted,
    'privacyVersion', v_privacy_version
  );
end;
$$;

create or replace function public.accept_media_privacy()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
begin
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;

  insert into public.legal_acceptances (user_id, document_type, version)
  select v_user_id, document_type, version
  from public.legal_document_versions
  where document_type = 'privacy' and is_current
  on conflict (user_id, document_type, version) do nothing;

  return public.get_media_account_status();
end;
$$;

create or replace function public.get_current_legal_status()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_created_at timestamptz;
  v_privacy public.legal_document_versions;
  v_terms public.legal_document_versions;
  v_privacy_accepted boolean := false;
  v_terms_accepted boolean := false;
begin
  select * into v_privacy from public.legal_document_versions
  where document_type = 'privacy' and is_current;
  select * into v_terms from public.legal_document_versions
  where document_type = 'terms' and is_current;

  if v_user_id is null then
    return jsonb_build_object(
      'authenticated', false,
      'accepted', false,
      'privacyVersion', v_privacy.version,
      'termsVersion', v_terms.version
    );
  end if;

  select created_at into v_created_at from auth.users where id = v_user_id;
  select exists (
    select 1 from public.legal_acceptances
    where user_id = v_user_id
      and document_type = 'terms'
      and version = v_terms.version
  ) into v_terms_accepted;
  select exists (
    select 1 from public.legal_acceptances
    where user_id = v_user_id
      and document_type = 'privacy'
      and (
        version = v_privacy.version
        or (
          v_privacy.account_gate_from is not null
          and v_created_at < v_privacy.account_gate_from
        )
      )
  ) into v_privacy_accepted;

  return jsonb_build_object(
    'authenticated', true,
    'accepted', v_privacy_accepted and v_terms_accepted,
    'privacyVersion', v_privacy.version,
    'termsVersion', v_terms.version
  );
end;
$$;

create or replace function public.commit_entry_media(
  p_user_id uuid,
  p_entry_id uuid,
  p_media_id uuid,
  p_storage_path text,
  p_byte_size integer,
  p_width integer,
  p_height integer,
  p_operation_id uuid,
  p_expected_media_id uuid default null,
  p_expected_version bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_existing public.entry_media;
  v_saved public.entry_media;
  v_tier text;
  v_count integer;
begin
  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text, 0));

  if not exists (
    select 1 from public.entries
    where id = p_entry_id and user_id = p_user_id
  ) then
    raise exception 'Entry not found' using errcode = 'P0002';
  end if;

  if p_storage_path <> p_user_id::text || '/' || p_entry_id::text || '/' || p_media_id::text || '.webp'
    or p_byte_size < 1 or p_byte_size > 1000000
    or p_width < 1 or p_width > 2500
    or p_height < 1 or p_height > 2500 then
    raise exception 'Invalid media metadata' using errcode = '22023';
  end if;

  select * into v_saved from public.entry_media where operation_id = p_operation_id;
  if found then
    if v_saved.user_id <> p_user_id or v_saved.entry_id <> p_entry_id then
      raise exception 'Invalid media operation' using errcode = '22023';
    end if;
    return jsonb_build_object('status', 'saved', 'media', to_jsonb(v_saved), 'oldPath', null);
  end if;

  select * into v_existing from public.entry_media where entry_id = p_entry_id for update;
  if found then
    if p_expected_media_id is null
      or p_expected_media_id <> v_existing.id
      or p_expected_version is null
      or p_expected_version <> v_existing.version then
      return jsonb_build_object('status', 'conflict', 'remote', to_jsonb(v_existing));
    end if;

    insert into public.media_cleanup_queue (user_id, storage_path, reason)
    values (p_user_id, v_existing.storage_path, 'replaced')
    on conflict (storage_path) do update
    set next_attempt_at = now(), updated_at = now();

    update public.entry_media
    set id = p_media_id,
        storage_path = p_storage_path,
        byte_size = p_byte_size,
        width = p_width,
        height = p_height,
        version = version + 1,
        operation_id = p_operation_id,
        updated_at = now()
    where entry_id = p_entry_id
    returning * into v_saved;

    return jsonb_build_object('status', 'saved', 'media', to_jsonb(v_saved), 'oldPath', v_existing.storage_path);
  end if;

  if p_expected_media_id is not null or p_expected_version is not null then
    return jsonb_build_object('status', 'conflict', 'remote', null);
  end if;

  v_tier := public.current_media_tier(p_user_id);
  select count(*) into v_count from public.entry_media where user_id = p_user_id;
  if v_tier = 'free' and v_count >= 10 then
    return jsonb_build_object('status', 'limit', 'storedCount', v_count, 'limit', 10);
  end if;

  insert into public.entry_media (
    id, user_id, entry_id, storage_path, byte_size, width, height, operation_id
  ) values (
    p_media_id, p_user_id, p_entry_id, p_storage_path, p_byte_size, p_width, p_height, p_operation_id
  ) returning * into v_saved;

  return jsonb_build_object('status', 'saved', 'media', to_jsonb(v_saved), 'oldPath', null);
end;
$$;

create or replace function public.remove_entry_media(
  p_user_id uuid,
  p_media_id uuid,
  p_expected_version bigint
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_existing public.entry_media;
begin
  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text, 0));
  select * into v_existing
  from public.entry_media
  where id = p_media_id and user_id = p_user_id
  for update;

  if not found then
    return jsonb_build_object('status', 'missing');
  end if;
  if v_existing.version <> p_expected_version then
    return jsonb_build_object('status', 'conflict', 'remote', to_jsonb(v_existing));
  end if;

  delete from public.entry_media where id = p_media_id;
  return jsonb_build_object('status', 'removed', 'storagePath', v_existing.storage_path);
end;
$$;

create or replace function public.queue_media_cleanup(
  p_user_id uuid,
  p_storage_path text,
  p_reason text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_reason not in ('abandoned', 'removed', 'replaced', 'entry-deleted', 'account-deleted') then
    raise exception 'Invalid cleanup reason' using errcode = '22023';
  end if;
  insert into public.media_cleanup_queue (user_id, storage_path, reason)
  values (p_user_id, p_storage_path, p_reason)
  on conflict (storage_path) do update
  set next_attempt_at = now(), updated_at = now();
end;
$$;

create or replace function public.complete_media_cleanup(p_storage_paths text[])
returns void
language sql
security definer
set search_path = ''
as $$
  delete from public.media_cleanup_queue where storage_path = any(p_storage_paths);
$$;

create or replace function public.fail_media_cleanup(p_storage_path text, p_error_code text)
returns void
language sql
security definer
set search_path = ''
as $$
  update public.media_cleanup_queue
  set attempts = attempts + 1,
      last_error_code = left(p_error_code, 80),
      next_attempt_at = now() + make_interval(mins => least(1440, (power(2, least(attempts + 1, 10)))::integer)),
      updated_at = now()
  where storage_path = p_storage_path;
$$;

create or replace function public.queue_deleted_entry_media()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.media_cleanup_queue (user_id, storage_path, reason)
  values (
    case when exists (select 1 from auth.users where id = old.user_id) then old.user_id else null end,
    old.storage_path,
    'entry-deleted'
  )
  on conflict (storage_path) do update
  set next_attempt_at = now(), updated_at = now();
  return old;
end;
$$;

create trigger queue_deleted_entry_media
before delete on public.entry_media
for each row execute function public.queue_deleted_entry_media();

create or replace function public.record_media_event(
  p_event_name text,
  p_operation_id uuid,
  p_entry_date date default null,
  p_size_bucket text default null,
  p_duration_bucket text default null,
  p_failure_category text default null
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_tier text;
  v_inserted bigint;
begin
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;
  if p_event_name not in (
    'photo_selected', 'photo_processing_completed', 'photo_processing_failed',
    'photo_upload_completed', 'photo_upload_failed', 'photo_replaced',
    'photo_removed', 'free_photo_limit_reached'
  ) then
    raise exception 'Unknown media event' using errcode = '22023';
  end if;
  if (select count(*) from public.media_events where user_id = v_user_id and occurred_at >= now() - interval '1 hour') >= 50 then
    return false;
  end if;

  v_tier := public.current_media_tier(v_user_id);
  insert into public.media_events (
    user_id, entry_date, event_name, operation_id, size_bucket,
    duration_bucket, failure_category, entitlement, dedupe_key
  ) values (
    v_user_id, p_entry_date, p_event_name, p_operation_id, p_size_bucket,
    p_duration_bucket, p_failure_category, v_tier,
    p_event_name || ':' || v_user_id::text || ':' || p_operation_id::text
  ) on conflict (dedupe_key) do nothing
  returning id into v_inserted;

  return v_inserted is not null;
end;
$$;

create or replace function public.get_entry_history(
  p_query text default null,
  p_from_date date default null,
  p_to_date date default null,
  p_before_date date default null,
  p_limit integer default 30
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_query text := nullif(btrim(p_query), '');
  v_items jsonb := '[]'::jsonb;
  v_has_more boolean := false;
  v_next_cursor date;
begin
  if v_user_id is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  if v_query is not null and char_length(v_query) > 200 then raise exception 'Search query is too long' using errcode = '22023'; end if;
  if p_limit is null or p_limit < 1 or p_limit > 50 then raise exception 'History page size must be between 1 and 50' using errcode = '22023'; end if;
  if p_from_date is not null and p_to_date is not null and p_from_date > p_to_date then raise exception 'History date range is invalid' using errcode = '22023'; end if;

  with candidates as (
    select e.entry_date, e.word_count, e.updated_at, e.word_count >= 100 as completed,
      regexp_replace(e.content, E'[\n\r\t ]+', ' ', 'g') as normalized_content,
      m.id as media_id, m.storage_path, m.byte_size, m.width, m.height,
      m.version as media_version, m.created_at as media_created_at, m.updated_at as media_updated_at
    from public.entries e
    left join public.entry_media m on m.entry_id = e.id
    where e.user_id = v_user_id
      and (p_from_date is null or e.entry_date >= p_from_date)
      and (p_to_date is null or e.entry_date <= p_to_date)
      and (p_before_date is null or e.entry_date < p_before_date)
      and (v_query is null or strpos(lower(e.content), lower(v_query)) > 0)
    order by e.entry_date desc limit p_limit + 1
  ), ranked as (
    select c.*, row_number() over (order by c.entry_date desc) as row_number from candidates c
  ), page as (
    select r.*,
      case
        when r.normalized_content = '' and r.media_id is not null then 'Photo saved; no words yet.'
        when v_query is null then left(r.normalized_content, 180)
        else substring(r.normalized_content from greatest(strpos(lower(r.normalized_content), lower(v_query)) - 80, 1) for 240)
      end as excerpt
    from ranked r where r.row_number <= p_limit
  )
  select coalesce(jsonb_agg(jsonb_build_object(
      'entryDate', p.entry_date, 'excerpt', p.excerpt, 'wordCount', p.word_count,
      'completed', p.completed, 'updatedAt', p.updated_at,
      'media', case when p.media_id is null then null else jsonb_build_object(
        'id', p.media_id, 'storagePath', p.storage_path, 'mimeType', 'image/webp',
        'byteSize', p.byte_size, 'width', p.width, 'height', p.height,
        'version', p.media_version, 'createdAt', p.media_created_at, 'updatedAt', p.media_updated_at
      ) end
    ) order by p.entry_date desc), '[]'::jsonb),
    (select count(*) > p_limit from candidates), min(p.entry_date)
  into v_items, v_has_more, v_next_cursor from page p;

  return jsonb_build_object('items', v_items, 'hasMore', v_has_more,
    'nextCursor', case when v_has_more then v_next_cursor else null end);
end;
$$;

create or replace function public.get_habit_dashboard(p_month date default null)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid(); v_profile public.profiles; v_today date;
  v_month_start date; v_month_end date; v_current_month_start date; v_year_start date;
  v_current_streak integer := 0; v_longest_streak integer := 0; v_first_entry date;
  v_last_completed date; v_last_writing date; v_total_words bigint := 0;
  v_total_completed integer := 0; v_total_writing integer := 0; v_last_seven_writing integer := 0;
  v_month_words bigint := 0; v_month_completed integer := 0; v_month_writing integer := 0;
  v_year_words bigint := 0; v_year_completed integer := 0; v_year_writing integer := 0;
  v_calendar jsonb := '[]'::jsonb;
begin
  if v_user_id is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  select * into v_profile from public.profiles where user_id = v_user_id;
  if not found then raise exception 'Profile required' using errcode = 'P0002'; end if;
  v_today := (now() at time zone v_profile.timezone)::date;
  v_month_start := date_trunc('month', coalesce(p_month, v_today))::date;
  v_month_end := (v_month_start + interval '1 month - 1 day')::date;
  v_current_month_start := date_trunc('month', v_today)::date;
  v_year_start := date_trunc('year', v_today)::date;
  select current_streak, longest_streak into v_current_streak, v_longest_streak from public.habit_streaks(v_user_id, v_today);
  select min(entry_date), max(entry_date) filter (where word_count >= 100),
    max(entry_date) filter (where public.entry_has_visible_content(content)), coalesce(sum(word_count), 0),
    count(*) filter (where word_count >= 100), count(*) filter (where public.entry_has_visible_content(content))
  into v_first_entry, v_last_completed, v_last_writing, v_total_words, v_total_completed, v_total_writing
  from public.entries where user_id = v_user_id;
  select count(*) filter (where public.entry_has_visible_content(content)) into v_last_seven_writing
  from public.entries where user_id = v_user_id and entry_date between v_today - 6 and v_today;
  select coalesce(sum(word_count), 0), count(*) filter (where word_count >= 100),
    count(*) filter (where public.entry_has_visible_content(content))
  into v_month_words, v_month_completed, v_month_writing from public.entries
  where user_id = v_user_id and entry_date between v_current_month_start and v_today;
  select coalesce(sum(word_count), 0), count(*) filter (where word_count >= 100),
    count(*) filter (where public.entry_has_visible_content(content))
  into v_year_words, v_year_completed, v_year_writing from public.entries
  where user_id = v_user_id and entry_date between v_year_start and v_today;
  select coalesce(jsonb_agg(jsonb_build_object(
    'entryDate', e.entry_date, 'wordCount', e.word_count, 'completed', e.word_count >= 100,
    'hasWriting', public.entry_has_visible_content(e.content),
    'hasPhoto', exists(select 1 from public.entry_media m where m.entry_id = e.id)
  ) order by e.entry_date), '[]'::jsonb) into v_calendar
  from public.entries e where e.user_id = v_user_id and e.entry_date between v_month_start and v_month_end;
  return jsonb_build_object(
    'today', v_today, 'visibleMonth', v_month_start, 'currentStreak', v_current_streak,
    'longestStreak', v_longest_streak, 'firstEntryDate', v_first_entry, 'lastCompletedDate', v_last_completed,
    'missedDays', case when v_last_completed is null then 0 else greatest(v_today - v_last_completed - 1, 0) end,
    'lastWelcomeBackDate', v_profile.last_welcome_back_date, 'totalWords', v_total_words,
    'totalCompletedDays', v_total_completed, 'monthWords', v_month_words,
    'monthCompletedDays', v_month_completed, 'monthElapsedDays', extract(day from v_today)::integer,
    'yearWords', v_year_words, 'yearCompletedDays', v_year_completed,
    'yearElapsedDays', extract(doy from v_today)::integer, 'calendar', v_calendar,
    'totalWritingDays', v_total_writing, 'lastSevenWritingDays', v_last_seven_writing,
    'monthWritingDays', v_month_writing, 'yearWritingDays', v_year_writing,
    'mostRecentWritingDate', v_last_writing,
    'daysSinceLastWriting', case when v_last_writing is null then 0 else greatest(v_today - v_last_writing, 0) end,
    'monthlyChapterEligible', v_month_writing >= 10,
    'monthlyChapterDaysRemaining', greatest(10 - v_month_writing, 0)
  );
end;
$$;

create or replace function public.media_cleanup_candidates(p_limit integer default 100)
returns table (storage_path text, attempts integer)
language sql
security definer
set search_path = ''
as $$
  select q.storage_path, q.attempts
  from public.media_cleanup_queue q
  where q.next_attempt_at <= now()
  order by q.next_attempt_at, q.id
  limit least(greatest(p_limit, 1), 500);
$$;

create or replace function public.orphaned_media_objects(p_limit integer default 100)
returns table (storage_path text)
language sql
security definer
set search_path = ''
as $$
  select o.name
  from storage.objects o
  left join public.entry_media m on m.storage_path = o.name
  where o.bucket_id = 'journal-media'
    and m.id is null
    and o.created_at < now() - interval '1 hour'
  order by o.created_at
  limit least(greatest(p_limit, 1), 500);
$$;

create or replace function public.user_media_storage_paths(p_user_id uuid)
returns table (storage_path text)
language sql
security definer
set search_path = ''
as $$
  select o.name
  from storage.objects o
  where o.bucket_id = 'journal-media'
    and (storage.foldername(o.name))[1] = p_user_id::text;
$$;

revoke all on function public.owns_journal_media_object(text) from public;
revoke all on function public.current_media_tier(uuid) from public;
revoke all on function public.get_media_account_status() from public;
revoke all on function public.accept_media_privacy() from public;
revoke all on function public.commit_entry_media(uuid, uuid, uuid, text, integer, integer, integer, uuid, uuid, bigint) from public;
revoke all on function public.remove_entry_media(uuid, uuid, bigint) from public;
revoke all on function public.queue_media_cleanup(uuid, text, text) from public;
revoke all on function public.complete_media_cleanup(text[]) from public;
revoke all on function public.fail_media_cleanup(text, text) from public;
revoke all on function public.queue_deleted_entry_media() from public;
revoke all on function public.record_media_event(text, uuid, date, text, text, text) from public;
revoke all on function public.media_cleanup_candidates(integer) from public;
revoke all on function public.orphaned_media_objects(integer) from public;
revoke all on function public.user_media_storage_paths(uuid) from public;

grant execute on function public.owns_journal_media_object(text) to authenticated;
grant execute on function public.get_media_account_status() to authenticated;
grant execute on function public.accept_media_privacy() to authenticated;
grant execute on function public.record_media_event(text, uuid, date, text, text, text) to authenticated;
grant execute on function public.commit_entry_media(uuid, uuid, uuid, text, integer, integer, integer, uuid, uuid, bigint) to service_role;
grant execute on function public.current_media_tier(uuid) to service_role;
grant execute on function public.remove_entry_media(uuid, uuid, bigint) to service_role;
grant execute on function public.queue_media_cleanup(uuid, text, text) to service_role;
grant execute on function public.complete_media_cleanup(text[]) to service_role;
grant execute on function public.fail_media_cleanup(text, text) to service_role;
grant execute on function public.media_cleanup_candidates(integer) to service_role;
grant execute on function public.orphaned_media_objects(integer) to service_role;
grant execute on function public.user_media_storage_paths(uuid) to service_role;

revoke all on function public.get_entry_history(text, date, date, date, integer) from public;
grant execute on function public.get_entry_history(text, date, date, date, integer) to authenticated;
revoke all on function public.get_habit_dashboard(date) from public;
grant execute on function public.get_habit_dashboard(date) to authenticated;

create or replace view public.media_founder_metrics
with (security_invoker = true)
as
select
  count(distinct m.user_id) as users_with_photos,
  count(*) as attached_photos,
  coalesce(sum(m.byte_size), 0) as stored_bytes,
  count(*) filter (where public.current_media_tier(m.user_id) = 'free') as free_photos,
  count(*) filter (where public.current_media_tier(m.user_id) = 'premium') as premium_photos,
  (select count(*) from public.media_cleanup_queue) as cleanup_backlog
from public.entry_media m;

revoke all on table public.media_founder_metrics from anon, authenticated;
grant select on table public.media_founder_metrics to service_role;
